# Generated by Django 4.0.8 on 2022-12-31 01:06

from django.db import migrations, models
# Generated by Django 4.0.5 on 2023-01-01 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=1000, verbose_name='Stock Name')),
                ('symbol', models.TextField(max_length=100, verbose_name='Ticker Symbol')),
                ('tags', models.TextField(help_text="Enter additional keywords to use in the search ('#XBox', 'IOS')", max_length=1000, verbose_name='Search Tags')),
                ('active', models.BooleanField(default=True, help_text='Check to activate the stock or uncheck to deactivate the stock.', verbose_name='Activate or Deactivate')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
